name: Java CI with Gradle

on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20

      - name: "Run JUnit Tests"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: "Build Project"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build